### ISSUE TITLE
Starting and running the project

### ISSUE THREAD

**Issue by AylinNaebzadeh** [wingsico/ll1#1]
Hello. How can we run this app to see the result? I am just a beginner in JS field. After I run the ```npm install``` command to install the packages, and run the ```index.js``` file to see the results, the below error is shown up:
```
D:\Compiler\ll1>node ./test/index.js
D:\Compiler\ll1\test\index.js:2
const filePath = path.resolve(__dirname, './g.txt');
                      ^

TypeError: path.resolve is not a function
    at Object.<anonymous> (D:\Compiler\ll1\test\index.js:2:23)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.14.0
```
Thanks!

**Comment by wzono** [comment]
> Hello. How can we run this app to see the result? I am just a beginner in JS field. After I run the `npm install` command to install the packages, and run the `index.js` file to see the results, the below error is shown up:
> 
> ```
> D:\Compiler\ll1>node ./test/index.js
> D:\Compiler\ll1\test\index.js:2
> const filePath = path.resolve(__dirname, './g.txt');
>                       ^
> 
> TypeError: path.resolve is not a function
>     at Object.<anonymous> (D:\Compiler\ll1\test\index.js:2:23)
>     at Module._compile (node:internal/modules/cjs/loader:1226:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
>     at Module.load (node:internal/modules/cjs/loader:1089:32)
>     at Module._load (node:internal/modules/cjs/loader:930:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:23:47
> 
> Node.js v18.14.0
> ```
> 
> Thanks!

It's an old project, I try it just now. But I can not get the error that you met..

Are you sure that node_modules folder existed?

**Comment by AylinNaebzadeh** [comment]
I think you have added some small changes to your project recently...
I pulled the current changes. And run the **index.js** file which is located in the root of project not in **test** folder, and also add the path in which **g.txt** file is located.
```
const fs = require('fs');
const path = require('./test/g.txt');
const Grammar = require('./lib/class/Grammar');
const utils = require('./lib/utils');
const removeLeftRecursion = require('./lib/components/removeLeftRecursion');
const removeLeftDivisor = require('./lib/components/removeLeftDivisor');
const simplify = require('./lib/components/simplify');
```
And now the below error is shown in terminal:
```
D:\Compiler\ll1>node index.js    
D:\Compiler\ll1\test\g.txt:1
S->AdS|Ba;
  ^

SyntaxError: Unexpected token '>'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1149:20)
    at Module._compile (node:internal/modules/cjs/loader:1190:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\Compiler\ll1\index.js:2:14)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)

Node.js v18.14.0
```
![image](https://github.com/wingsico/ll1/assets/74285546/423fa197-b5e7-4d96-92c5-216cf008edcf)

**Comment by wzono** [comment]
> I think you have added some small changes to your project recently... I pulled the current changes. And run the **index.js** file which is located in the root of project not in **test** folder, and also add the path in which **g.txt** file is located.
> 
> ```
> const fs = require('fs');
> const path = require('./test/g.txt');
> const Grammar = require('./lib/class/Grammar');
> const utils = require('./lib/utils');
> const removeLeftRecursion = require('./lib/components/removeLeftRecursion');
> const removeLeftDivisor = require('./lib/components/removeLeftDivisor');
> const simplify = require('./lib/components/simplify');
> ```
> 
> And now the below error is shown in terminal:
> 
> ```
> D:\Compiler\ll1>node index.js    
> D:\Compiler\ll1\test\g.txt:1
> S->AdS|Ba;
>   ^
> 
> SyntaxError: Unexpected token '>'
>     at internalCompileFunction (node:internal/vm:73:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1149:20)
>     at Module._compile (node:internal/modules/cjs/loader:1190:27)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
>     at Module.load (node:internal/modules/cjs/loader:1089:32)
>     at Module._load (node:internal/modules/cjs/loader:930:12)
>     at Module.require (node:internal/modules/cjs/loader:1113:19)
>     at require (node:internal/modules/cjs/helpers:103:18)
>     at Object.<anonymous> (D:\Compiler\ll1\index.js:2:14)
>     at Module._compile (node:internal/modules/cjs/loader:1226:14)
> 
> Node.js v18.14.0
> ```
> 
> ![image](https://user-images.githubusercontent.com/74285546/241887500-423fa197-b5e7-4d96-92c5-216cf008edcf.png)

I found a problem with this line of code, did you change the index.js file?

```
const fs = require('fs');
const path = require('./test/g.txt');      <------------------------- this line should be "require('path')", "path" is a node internal library, you should not modify it.
const Grammar = require('./lib/class/Grammar');
const utils = require('./lib/utils');
const removeLeftRecursion = require('./lib/components/removeLeftRecursion');
const removeLeftDivisor = require('./lib/components/removeLeftDivisor');
const simplify = require('./lib/components/simplify');
```

If you want to test the execution of the code, you can try running this command directly:

```
npm run test
```

Then you will get the right output:

<img width="384" alt="CleanShot 2023-05-31 at 09 34 04@2x" src="https://github.com/wingsico/ll1/assets/26498668/03033981-99b9-4b99-95c0-575044e064f8">

**Comment by AylinNaebzadeh** [comment]
Thanks for your help.
